# Generated by Django 3.2.3 on 2021-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20210516_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='default/profile.jpg', upload_to='image/'),
        ),
    ]
