# Generated by Django 3.2.3 on 2021-05-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_alter_faculty_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='image',
        ),
    ]
