# Generated by Django 3.2.3 on 2021-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_remove_faculty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(default='default/profile.jpg', upload_to=''),
        ),
    ]
