# Generated by Django 3.2.3 on 2021-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_faculty_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='branch',
            field=models.CharField(default='Computer Science', max_length=200),
        ),
    ]
