# Generated by Django 3.2.3 on 2021-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_alter_faculty_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(default='default/profile.jpg', upload_to='image/'),
        ),
    ]
