# Generated by Django 3.2.3 on 2021-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_alter_faculty_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(default='default/profile.jpg', upload_to='image/image/'),
        ),
    ]
