# Generated by Django 3.2.3 on 2021-05-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_alter_faculty_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
