# Generated by Django 3.2.3 on 2021-05-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_email', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.FileField(blank=True, upload_to='static/notes/')),
                ('video', models.FileField(upload_to='static/videos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
