# Generated by Django 3.2.3 on 2021-05-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0019_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='notes',
            field=models.FileField(blank=True, upload_to='image/notes/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='image/video/'),
        ),
    ]
