# Generated by Django 3.2.3 on 2021-05-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_auto_20210518_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
