# Generated by Django 3.2.3 on 2021-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
